[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["parkgood1020 <parkgood1020@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
